stages:
  - mirror
  - test
  - build
  - deploy
  - release
  - docstats

variables:
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"
  GITHUB_OAUTH_TOKEN: "$GITHUB_OAUTH_TOKEN"

github_mirror:
  stage: mirror
  only:
    - master
    - develop
  tags:
    - key_github
  script:
    - git checkout master
    - git pull origin master
    - git push git@github.com:namboy94/comunio-manager.git master --force
    - git checkout develop
    - git pull origin develop
    - git push git@github.com:namboy94/comunio-manager.git develop --force

run_unit_tests_python_2:
  stage: test
  tags:
    - linux
    - python
  script:
    - 3to2 . --write
    - python2 setup.py test

run_unit_tests_python_3:
  stage: test
  tags:
    - linux
    - python
  script:
    - python3 setup.py test

pyinstaller_linux:
  stage: build
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 builder.py build pyinstaller_linux
  artifacts:
    paths:
      - build/gitlab_build_scripts/*

pyinstaller_linux:
  stage: build
  only:
    - master
  tags:
    - windows
    - python
  script:
    - python builder.py build pyinstaller_linux
  artifacts:
    paths:
      - build/gitlab_build_scripts/*

source_dist:
  stage: deploy
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py register sdist upload

binary_3_dist:
  stage: deploy
  only:
    - master
  tags:
    - linux
    - python
  script:
    - python3 setup.py bdist_wheel upload

binary_2_dist:
  stage: deploy
  only:
    - master
  tags:
    - python
    - linux
  script:
    - 3to2 . --write
    - python2 setup.py bdist_wheel
    - twine upload dist/*

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python
    - linux
  script:
    - python3 builder.py github-release

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python
    - linux
  script:
    - python3 builder.py gitlab-release

generate_documentation_pdf:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - python
    - linux
  script:
    - cd doc
    - make buildsource
    - make latexpdf
    - rsync -av build/latex/ComunioManager.pdf /var/www/docs.namibsun.net/public_html/pdf_docs/comunio-manager.pdf --delete-before
  artifacts:
    paths:
      - doc/build/latex/ComunioManager.pdf

generate_documentation_html:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - python
    - linux
  script:
    - cd doc
    - make buildsource
    - make html
    - rsync -av build/html/ /var/www/docs.namibsun.net/public_html/html_docs/comunio-manager --delete-before
  artifacts:
    paths:
      - doc/build/html

gitstats:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - linux
  script:
    - gitstats . git_stats
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/gitstats/comunio-manager --delete-before
  artifacts:
    paths:
      - git_stats

git_stats:
  stage: docstats
  only:
    - master
    - develop
  tags:
    - linux
  script:
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/comunio-manager --delete-before
  artifacts:
    paths:
      - git_stats