stages:
  - mirror
  - setup
  - test
  - deploy
  - docstats

clone_master:
  stage: mirror
  only:
    - master
    - develop
  script:
    - git checkout master
    - git pull origin master
    - git push -u git@github.com:namboy94/comunio-manager.git master --force
    - git checkout develop
    - git pull origin develop
    - git push -u git@github.com:namboy94/comunio-manager.git develop --force

install_python2_dependencies:
  stage: setup
  only:
    - master
    - develop
  script:
    - 3to2 . --write
    - python2 setup.py install --user
    - pip2 uninstall comunio -y

install_python3_dependencies:
  stage: setup
  only:
    - master
    - develop
  script:
    - python3 setup.py install --user
    - pip3 uninstall comunio -y

run_unit_tests_python_2:
  stage: test
  only:
    - master
    - develop
  script:
    - 3to2 . --write
    - python2 setup.py test

run_unit_tests_python_3:
  stage: test
  only:
    - master
    - develop
  script:
    - python3 setup.py test

source_dist:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py register sdist upload

binary_3_dist:
  stage: deploy
  only:
    - master
  script:
    - python3 setup.py bdist_wheel upload

binary_2_dist:
  stage: deploy
  only:
    - master
  script:
    - 3to2 . --write
    - python2 setup.py bdist_wheel upload

generate_documentation_pdf:
  stage: docstats
  only:
    - master
    - develop
  script:
    - cd doc
    - make buildsource
    - make latexpdf
    - rsync -av build/latex/ComunioManager.pdf /var/www/docs.namibsun.net/public_html/pdf_docs/comunio-manager.pdf --delete-before
  artifacts:
    paths:
      - doc/build/latex/ComunioManager.pdf

generate_documentation_html:
  stage: docstats
  only:
    - master
    - develop
  script:
    - cd doc
    - make buildsource
    - make html
    - rsync -av build/html/ /var/www/docs.namibsun.net/public_html/html_docs/comunio-manager --delete-before
  artifacts:
    paths:
      - doc/build/html

gitstats:
  stage: docstats
  only:
    - master
    - develop
  script:
    - gitstats . git_stats
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/gitstats/comunio-manager --delete-before
  artifacts:
    paths:
      - git_stats

git_stats:
  stage: docstats
  only:
    - master
    - develop
  script:
    - git_stats generate
    - rsync -av git_stats/ /var/www/gitstats.namibsun.net/public_html/git_stats/comunio-manager --delete-before
  artifacts:
    paths:
      - git_stats