# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StatisticsWindow(object):
    def setupUi(self, StatisticsWindow):
        StatisticsWindow.setObjectName("StatisticsWindow")
        StatisticsWindow.resize(896, 614)
        self.centralwidget = QtWidgets.QWidget(StatisticsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.total_assets_display = QtWidgets.QLabel(self.centralwidget)
        self.total_assets_display.setObjectName("total_assets_display")
        self.gridLayout.addWidget(self.total_assets_display, 1, 9, 1, 1)
        self.greeting_label = QtWidgets.QLabel(self.centralwidget)
        self.greeting_label.setObjectName("greeting_label")
        self.gridLayout.addWidget(self.greeting_label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 3)
        self.team_value_display = QtWidgets.QLabel(self.centralwidget)
        self.team_value_display.setObjectName("team_value_display")
        self.gridLayout.addWidget(self.team_value_display, 1, 7, 1, 1)
        self.cash_display = QtWidgets.QLabel(self.centralwidget)
        self.cash_display.setObjectName("cash_display")
        self.gridLayout.addWidget(self.cash_display, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 9, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 8, 1, 1)
        self.balance_display = QtWidgets.QLabel(self.centralwidget)
        self.balance_display.setObjectName("balance_display")
        self.gridLayout.addWidget(self.balance_display, 1, 11, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 11, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 4, 1, 1)
        self.player_table = QtWidgets.QTreeWidget(self.centralwidget)
        self.player_table.setMinimumSize(QtCore.QSize(878, 327))
        self.player_table.setObjectName("player_table")
        self.gridLayout.addWidget(self.player_table, 2, 0, 1, 13)
        self.points_graph = QtWidgets.QLabel(self.centralwidget)
        self.points_graph.setMinimumSize(QtCore.QSize(0, 192))
        self.points_graph.setObjectName("points_graph")
        self.gridLayout.addWidget(self.points_graph, 3, 2, 5, 2)
        self.value_graph = QtWidgets.QLabel(self.centralwidget)
        self.value_graph.setObjectName("value_graph")
        self.gridLayout.addWidget(self.value_graph, 3, 5, 5, 7)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.player_name_label = QtWidgets.QLabel(self.centralwidget)
        self.player_name_label.setObjectName("player_name_label")
        self.gridLayout_2.addWidget(self.player_name_label, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.player_points_label = QtWidgets.QLabel(self.centralwidget)
        self.player_points_label.setObjectName("player_points_label")
        self.gridLayout_2.addWidget(self.player_points_label, 2, 1, 1, 1)
        self.player_position_label = QtWidgets.QLabel(self.centralwidget)
        self.player_position_label.setObjectName("player_position_label")
        self.gridLayout_2.addWidget(self.player_position_label, 1, 1, 1, 1)
        self.player_value_label = QtWidgets.QLabel(self.centralwidget)
        self.player_value_label.setObjectName("player_value_label")
        self.gridLayout_2.addWidget(self.player_value_label, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        StatisticsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StatisticsWindow)
        self.statusbar.setObjectName("statusbar")
        StatisticsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StatisticsWindow)
        QtCore.QMetaObject.connectSlotsByName(StatisticsWindow)

    def retranslateUi(self, StatisticsWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticsWindow.setWindowTitle(_translate("StatisticsWindow", "MainWindow"))
        self.total_assets_display.setText(_translate("StatisticsWindow", "0€"))
        self.greeting_label.setText(_translate("StatisticsWindow", "Comunio Statistics for <username>"))
        self.label_3.setText(_translate("StatisticsWindow", "Cash"))
        self.label_2.setText(_translate("StatisticsWindow", "Team Value"))
        self.team_value_display.setText(_translate("StatisticsWindow", "0€"))
        self.cash_display.setText(_translate("StatisticsWindow", "0€"))
        self.label.setText(_translate("StatisticsWindow", "Total Assets"))
        self.balance_display.setText(_translate("StatisticsWindow", "0€"))
        self.label_4.setText(_translate("StatisticsWindow", "Balance"))
        self.player_table.headerItem().setText(0, _translate("StatisticsWindow", "Position"))
        self.player_table.headerItem().setText(1, _translate("StatisticsWindow", "Player"))
        self.player_table.headerItem().setText(2, _translate("StatisticsWindow", "Points"))
        self.player_table.headerItem().setText(3, _translate("StatisticsWindow", "Initial Value"))
        self.player_table.headerItem().setText(4, _translate("StatisticsWindow", "Yesterday\'s Value"))
        self.player_table.headerItem().setText(5, _translate("StatisticsWindow", "Today\'s Value"))
        self.player_table.headerItem().setText(6, _translate("StatisticsWindow", "Total Value Change"))
        self.player_table.headerItem().setText(7, _translate("StatisticsWindow", "Value Tendency"))
        self.points_graph.setText(_translate("StatisticsWindow", "<html><head/><body><p align=\"center\">Points</p></body></html>"))
        self.value_graph.setText(_translate("StatisticsWindow", "<html><head/><body><p align=\"center\">Values</p></body></html>"))
        self.label_6.setText(_translate("StatisticsWindow", "Value"))
        self.player_name_label.setText(_translate("StatisticsWindow", "-"))
        self.label_5.setText(_translate("StatisticsWindow", "Name"))
        self.label_7.setText(_translate("StatisticsWindow", "Position"))
        self.label_11.setText(_translate("StatisticsWindow", "Points"))
        self.player_points_label.setText(_translate("StatisticsWindow", "-"))
        self.player_position_label.setText(_translate("StatisticsWindow", "-"))
        self.player_value_label.setText(_translate("StatisticsWindow", "-"))

